#!/usr/bin/env python
# coding: utf-8

import os
import sushi

from docopt import docopt
from sushi.cli import Cli

doc = """Sushi, a special Python package cookchef.

Usage:
  sushi craft <path> [--recipe=<name>]
  sushi learn <path>
  sushi forget <name>
  sushi cookbook
  sushi -h | --help
  sushi -v | --version

Options:
  --recipe=<name>     Select recipe
  -h --help           Show help
  -v --version        Show version

Examples:
  sushi learn basic.tar.gz
  sushi learn http+https://github.com/Socketubs/Sushi/raw/master/recipes/django.tar.gz
  sushi craft hellodjango --recipe django
"""

if __name__ == '__main__':
	args = docopt(doc, version=sushi.__version__)
	cli = Cli(**args)
	cli.start()
