#!/usr/bin/env python
# coding: utf-8

import os
import sushi

from docopt import docopt
from sushi.cli import Cli

doc = """sushi, mininal python bundler.

Usage:
  sushi init <name>
  sushi add <path>
  sushi del <name>
  sushi (list|licenses)
  sushi -h | --help
  sushi -v | --version

Options:
  -h --help        Show help
  -v --version     Show version
"""

if __name__ == '__main__':
	args = docopt(doc, version=sushi.__version__)
	cli = Cli(**args)
	cli.start()
